# Generated by Django 4.1.7 on 2023-03-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="gifs",
        ),
        migrations.AddField(
            model_name="gif",
            name="categories",
            field=models.ManyToManyField(related_name="gifs", to="gifs.category"),
        ),
    ]
