# Generated by Django 4.1.7 on 2023-03-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifs", "0002_remove_category_gifs_gif_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="gif",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
